export const A4_DOCUMENT_WIDTH = 794;
export const A4_DOCUMENT_HEIGHT = 1122;
export const DOCUMENT_FRAME_BORDER_WIDTH = 2;
export const PREVIEW_VIEWPORT_HORIZONTAL_GUTTER = 24;
export const PREVIEW_DOCUMENT_FRAME_WIDTH =
  A4_DOCUMENT_WIDTH + DOCUMENT_FRAME_BORDER_WIDTH;
export const PREVIEW_DOCUMENT_FRAME_HEIGHT =
  A4_DOCUMENT_HEIGHT + DOCUMENT_FRAME_BORDER_WIDTH;
