/**
 * Setup Razorpay Test Plans
 *
 * Creates all subscription plans in Razorpay (test mode) and prints the
 * env-var block you need to paste into your .env file.
 *
 * Usage:
 *   npx tsx scripts/setup-razorpay-plans.ts
 *
 * Prerequisites:
 *   RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET must already be set in .env
 */

import "dotenv/config";

const KEY_ID = process.env.RAZORPAY_KEY_ID;
const KEY_SECRET = process.env.RAZORPAY_KEY_SECRET;

if (!KEY_ID || !KEY_SECRET) {
  console.error(
    "❌ Set RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET in .env before running this script.",
  );
  process.exit(1);
}

const AUTH = Buffer.from(`${KEY_ID}:${KEY_SECRET}`).toString("base64");

interface PlanSpec {
  envKey: string;
  name: string;
  period: "monthly" | "yearly";
  amountPaise: number;
}

const PLANS: PlanSpec[] = [
  {
    envKey: "RAZORPAY_PLAN_STARTER_MONTHLY",
    name: "Slipwise Starter Monthly",
    period: "monthly",
    amountPaise: 99_900,
  },
  {
    envKey: "RAZORPAY_PLAN_STARTER_YEARLY",
    name: "Slipwise Starter Yearly",
    period: "yearly",
    amountPaise: 999_000,
  },
  {
    envKey: "RAZORPAY_PLAN_PRO_MONTHLY",
    name: "Slipwise Pro Monthly",
    period: "monthly",
    amountPaise: 299_900,
  },
  {
    envKey: "RAZORPAY_PLAN_PRO_YEARLY",
    name: "Slipwise Pro Yearly",
    period: "yearly",
    amountPaise: 2_999_000,
  },
  {
    envKey: "RAZORPAY_PLAN_ENTERPRISE_MONTHLY",
    name: "Slipwise Enterprise Monthly",
    period: "monthly",
    amountPaise: 999_900,
  },
  {
    envKey: "RAZORPAY_PLAN_ENTERPRISE_YEARLY",
    name: "Slipwise Enterprise Yearly",
    period: "yearly",
    amountPaise: 9_999_000,
  },
];

async function createPlan(spec: PlanSpec): Promise<string> {
  const res = await fetch("https://api.razorpay.com/v1/plans", {
    method: "POST",
    headers: {
      Authorization: `Basic ${AUTH}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      period: spec.period,
      interval: 1,
      item: {
        name: spec.name,
        amount: spec.amountPaise,
        currency: "INR",
        description: `${spec.name} subscription`,
      },
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(
      `Failed to create plan "${spec.name}": ${res.status} ${JSON.stringify(err)}`,
    );
  }

  const data = (await res.json()) as { id: string };
  return data.id;
}

async function main() {
  console.log("🔧 Creating Razorpay subscription plans...\n");

  const envLines: string[] = [
    "",
    "# Razorpay Plan IDs (auto-generated by scripts/setup-razorpay-plans.ts)",
  ];

  for (const spec of PLANS) {
    const planId = await createPlan(spec);
    envLines.push(`${spec.envKey}=${planId}`);
    console.log(`  ✅ ${spec.name} → ${planId}`);
  }

  console.log("\n📋 Add these lines to your .env:\n");
  console.log(envLines.join("\n"));
  console.log("");
}

main().catch((err) => {
  console.error("❌ Script failed:", err);
  process.exit(1);
});
