import type { InvoiceDocument } from "@/features/docs/invoice/types";
import type { VoucherDocument } from "@/features/docs/voucher/types";
import type { SalarySlipDocument } from "@/features/docs/salary-slip/types";

const SAMPLE_BRANDING = {
  companyName: "Acme Corporation",
  address: "12 Business Park, Andheri East, Mumbai 400069",
  email: "billing@acmecorp.in",
  phone: "+91 98765 43210",
  accentColor: "#2563eb",
  logoDataUrl: undefined,
};

export const SAMPLE_INVOICE_DOCUMENT: InvoiceDocument = {
  templateId: "minimal",
  title: "Invoice",
  branding: SAMPLE_BRANDING,
  website: "www.acmecorp.in",
  businessTaxId: "22AAAAA0000A1Z5",
  clientName: "TechStart Solutions Pvt Ltd",
  clientAddress: "45 Startup Hub, Koramangala, Bengaluru 560034",
  clientEmail: "accounts@techstart.io",
  clientPhone: "+91 80000 12345",
  invoiceNumber: "INV-2025-0042",
  invoiceDate: "01 Apr 2025",
  dueDate: "30 Apr 2025",
  placeOfSupply: "Karnataka",
  currencyCode: "INR",
  lineItems: [
    {
      description: "Website Redesign — Discovery & UX",
      quantity: 1,
      unitPrice: 45000,
      taxRate: 18,
      discountAmount: 0,
      baseAmount: 45000,
      taxableAmount: 45000,
      taxAmount: 8100,
      lineTotal: 53100,
      unitPriceFormatted: "₹45,000.00",
      discountAmountFormatted: "₹0.00",
      baseAmountFormatted: "₹45,000.00",
      taxAmountFormatted: "₹8,100.00",
      lineTotalFormatted: "₹53,100.00",
    },
    {
      description: "Frontend Development (React / Next.js)",
      quantity: 1,
      unitPrice: 80000,
      taxRate: 18,
      discountAmount: 5000,
      baseAmount: 75000,
      taxableAmount: 75000,
      taxAmount: 13500,
      lineTotal: 88500,
      unitPriceFormatted: "₹80,000.00",
      discountAmountFormatted: "₹5,000.00",
      baseAmountFormatted: "₹75,000.00",
      taxAmountFormatted: "₹13,500.00",
      lineTotalFormatted: "₹88,500.00",
    },
    {
      description: "Monthly Maintenance & Support",
      quantity: 3,
      unitPrice: 8000,
      taxRate: 18,
      discountAmount: 0,
      baseAmount: 24000,
      taxableAmount: 24000,
      taxAmount: 4320,
      lineTotal: 28320,
      unitPriceFormatted: "₹8,000.00",
      discountAmountFormatted: "₹0.00",
      baseAmountFormatted: "₹24,000.00",
      taxAmountFormatted: "₹4,320.00",
      lineTotalFormatted: "₹28,320.00",
    },
  ],
  subtotal: 149000,
  totalDiscount: 5000,
  totalTax: 25920,
  extraCharges: 0,
  invoiceLevelDiscount: 0,
  grandTotal: 169920,
  amountPaid: 50000,
  balanceDue: 119920,
  subtotalFormatted: "₹1,49,000.00",
  totalDiscountFormatted: "₹5,000.00",
  totalTaxFormatted: "₹25,920.00",
  extraChargesFormatted: "₹0.00",
  invoiceLevelDiscountFormatted: "₹0.00",
  grandTotalFormatted: "₹1,69,920.00",
  amountPaidFormatted: "₹50,000.00",
  balanceDueFormatted: "₹1,19,920.00",
  amountInWords: "One Lakh Nineteen Thousand Nine Hundred and Twenty Rupees Only",
  notes: "Payment via NEFT/RTGS. Please include invoice number as reference.",
  terms: "Net 30. Late payments subject to 1.5% monthly interest.",
  bankName: "HDFC Bank",
  bankAccountNumber: "50100012345678",
  bankIfsc: "HDFC0001234",
  authorizedBy: "Rahul Mehta",
  visibility: {
    showAddress: true,
    showEmail: true,
    showPhone: true,
    showWebsite: true,
    showBusinessTaxId: true,
    showClientAddress: true,
    showClientEmail: true,
    showClientPhone: false,
    showClientTaxId: false,
    showShippingAddress: false,
    showDueDate: true,
    showPlaceOfSupply: true,
    showNotes: true,
    showTerms: true,
    showBankDetails: true,
    showSignature: true,
    showPaymentSummary: true,
  },
};

export const SAMPLE_VOUCHER_DOCUMENT: VoucherDocument = {
  templateId: "minimal-office",
  voucherType: "payment",
  title: "Payment Voucher",
  counterpartyLabel: "Paid To",
  branding: SAMPLE_BRANDING,
  voucherNumber: "PV-2025-0018",
  date: "05 Apr 2025",
  counterpartyName: "Office Supplies & Co.",
  amount: 12500,
  amountFormatted: "₹12,500.00",
  amountInWords: "Twelve Thousand Five Hundred Rupees Only",
  paymentMode: "Bank Transfer",
  referenceNumber: "UTR8821045632",
  purpose: "Purchase of stationery, printer cartridges, and office consumables for Q1 2025",
  notes: "Approved under quarterly office budget",
  approvedBy: "Priya Sharma",
  receivedBy: "Amit Patel",
  visibility: {
    showAddress: true,
    showEmail: true,
    showPhone: true,
    showPaymentMode: true,
    showReferenceNumber: true,
    showNotes: true,
    showApprovedBy: true,
    showReceivedBy: true,
    showSignatureArea: true,
  },
};

export const SAMPLE_SALARY_SLIP_DOCUMENT: SalarySlipDocument = {
  templateId: "corporate-clean",
  title: "Salary Slip",
  branding: SAMPLE_BRANDING,
  employeeName: "Arjun Krishnamurthy",
  employeeId: "EMP-0421",
  department: "Engineering",
  designation: "Senior Software Engineer",
  pan: "ABCPK1234D",
  uan: "100987654321",
  payPeriodLabel: "March 2025",
  payDate: "31 Mar 2025",
  workingDays: "26",
  paidDays: "26",
  leaveDays: "0",
  lossOfPayDays: "0",
  paymentMethod: "Bank Transfer",
  bankName: "ICICI Bank",
  bankAccountNumber: "123456789012",
  bankIfsc: "ICIC0001234",
  joiningDate: "15 Jun 2022",
  workLocation: "Bengaluru",
  earnings: [
    { label: "Basic Salary", amount: 60000, amountFormatted: "₹60,000.00" },
    { label: "House Rent Allowance", amount: 24000, amountFormatted: "₹24,000.00" },
    { label: "Special Allowance", amount: 18000, amountFormatted: "₹18,000.00" },
    { label: "Transport Allowance", amount: 3200, amountFormatted: "₹3,200.00" },
    { label: "Medical Allowance", amount: 1250, amountFormatted: "₹1,250.00" },
  ],
  deductions: [
    { label: "Provident Fund (Employee)", amount: 7200, amountFormatted: "₹7,200.00" },
    { label: "Professional Tax", amount: 200, amountFormatted: "₹200.00" },
    { label: "Income Tax (TDS)", amount: 4500, amountFormatted: "₹4,500.00" },
  ],
  totalEarnings: 106450,
  totalDeductions: 11900,
  netSalary: 94550,
  totalEarningsFormatted: "₹1,06,450.00",
  totalDeductionsFormatted: "₹11,900.00",
  netSalaryFormatted: "₹94,550.00",
  netSalaryInWords: "Ninety Four Thousand Five Hundred and Fifty Rupees Only",
  notes: "This is a system-generated document. No signature required.",
  preparedBy: "HR Department",
  visibility: {
    showAddress: true,
    showEmail: true,
    showPhone: false,
    showEmployeeId: true,
    showDepartment: true,
    showDesignation: true,
    showPan: true,
    showUan: true,
    showBankDetails: true,
    showJoiningDate: true,
    showWorkLocation: true,
    showAttendance: true,
    showNotes: true,
    showSignature: true,
  },
};
